function NDVI1 = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  NDVI1 = IMPORTFILE1(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  NDVI1 = IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  NDVI1 = importfile1("D:\Parsa_Global\course\NDVI.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Apr-2022 10:31:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["systemtime_start", "NDVI"];
opts.VariableTypes = ["datetime", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "systemtime_start", "InputFormat", "dd-MMM-yy");
opts = setvaropts(opts, "NDVI", "TrimNonNumeric", true);
opts = setvaropts(opts, "NDVI", "ThousandsSeparator", ",");

% Import the data
NDVI1 = readtable(filename, opts);

end